name: samplemainfile

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Choose the pipeline to run'
        required: true
        type: choice
        options:
          - deploy-test
          - deploy-prod

jobs:
  condition-set:
    runs-on: ubuntu-latest
    outputs:
      run-test: ${{ steps.set.outputs.run-test }}
      run-prod: ${{ steps.set.outputs.run-prod }}

    steps:
      - id: set
        run: |
          if [[ "${{ github.event.inputs.target }}" == "deploy-test" ]]; then
            echo "run-test=true" >> $GITHUB_OUTPUT
            echo "run-prod=false" >> $GITHUB_OUTPUT
          else
            echo "run-test=false" >> $GITHUB_OUTPUT
            echo "run-prod=true" >> $GITHUB_OUTPUT
          fi

      - name: Print selection
        run: echo "User selected ${{ github.event.inputs.target }}"
