name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Enter the domain for deployment'
        required: true
        default: 'staging.example.com'

jobs:
  show-domain:
    runs-on: ubuntu-latest
    steps:
      - name: Show selected domain
        run: echo "Deploying to ${{ github.event.inputs.domain }}"

  deploy:
    needs: show-domain
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to the selected domain
        run: |
          echo "Deploying to ${{ github.event.inputs.domain }}"
          # Add your deployment script here
