name: Master Workflow

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Choose the pipeline to run'
        required: true
        type: choice
        options:
          - pipeline-a
          - pipeline-b

jobs:
  condition-set:
    runs-on: ubuntu-latest
    outputs:
      run-a: ${{ steps.set.outputs.run-a }}
      run-b: ${{ steps.set.outputs.run-b }}

    steps:
      - id: set
        run: |
          if [[ "${{ github.event.inputs.target }}" == "pipeline-a" ]]; then
            echo "run-a=true" >> $GITHUB_OUTPUT
            echo "run-b=false" >> $GITHUB_OUTPUT
          else
            echo "run-a=false" >> $GITHUB_OUTPUT
            echo "run-b=true" >> $GITHUB_OUTPUT
          fi
