name: Pipeline A

on:
  workflow_run:
    workflows: ["Master Workflow"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'Master Workflow' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run only if Pipeline A was selected
        if: ${{ github.event.workflow_run.head_commit.message contains 'pipeline-a' }}
        run: echo "Running Pipeline A steps..."
